{% set name = "pyxley" %}
{% set version = "0.1.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "8d30f55b0a6bc4742f24a85c2afbdcd59e8480af5c84426d37254bd072e1c32d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - flask
    - pandas

test:
  imports:
    - pyxley
    - pyxley.charts
    - pyxley.charts.datamaps
    - pyxley.charts.datatables
    - pyxley.charts.mg
    - pyxley.charts.nvd3
    - pyxley.filters
    - pyxley.utils
  commands:
    - pyxapp -h

about:
  home: https://github.com/stitchfix/pyxley
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python tools for building Flask-based web applications'
  license_family: MIT
  dev_url: https://github.com/stitchfix/pyxley
  doc_url: https://pyxley.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
