travis:
  secure:
    BINSTAR_TOKEN: izF2V20ca9MwryrrIucjC6umNxkqAVssOuQXTd2V7LR9vooJfLj5xGp1MabDrB9G4/P9iWclBsVwQqiTlFvBu4nnrQcTQBugkjxKwcuCup9S3gvYlBNooVqWwYb9pp3OyR4e/gzbTKjq4FnpVkXzpP7RQf40nx/HdJzRZPkMtc6LXlFNiIuKQ6nIgNToVJucSW5wNl3t7eqfUWZUn9fDphQjpvWB/N0qUmCFsp8VROgEeCWogCpxjxfUFo/c+0WkAZSfZsueIRoQz4/rS3Hs9y4BC/0YWlKeyy3WJ0kKtjZOXiEaL25Grx+3HDgbKqKOS2Y3nQK4JZJW5y4myxSgIH0ACUT3B9adxkVUSzAlE5/TM64EmyiQJLFi6b5ySsQCENEhzeDH+Pouly5Lqk7qgRcms8tgBfSrEMv2erT/r8v8wMXD2KwzobZhOJB1KRU9bU6exS8zgoYWu0WYMpo5yVKeTsn8gXNH1ZRBhTDZzfZGeqqXmUBJTW5gDcgPeEIfvO/sduIYl0PKlSgYcXmBOcQnJyMbzwS5teSJBs5HtwiTD0FoIh/MUdBJr0SPmyHvVBzrDafW2Pn3eBH+d4IfI2Vdh44CBZzLSNsDpruI2eY6ZLquKBD/vP6JY3wU1+zzCR85yqpMQVg2+Cb4Awvb+voKOk1wcTIqNOg/aBy2pVI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
