travis:
  secure:
    BINSTAR_TOKEN: Twa2Wan9pDiItU7JjtDZca9FDQhuZNoDDnBZBZvvP5oPvjp7McEEGO2TVXckftEPwYjUShC07WceeQ7taJ+XDOd6vMCsrkwi6pnxSAKq7k80dq/5UdmzGeXYL+13gyr5cls3Yx/XgxEI65J6xE2v5Bb4Z18GU92X+BJDF1RCvkD/RWjdAH8kqjEXeIRwgle2NpeG7YDcWfJjbJxUidOW0nIFFo08kI0PVaaeHoRAT4WAqqjAkAR3EIwODT7X2bcC8fp0XA2y5cQ+vL/nmh533syi3siEnibZi9DNBRl8H7iyVzXZFopDd9Zo57CZjW2rMzsrgE4MW76I2lH7t0nHf9P1AWHJBMpqsD2GA9vf1yDcb4VDehMjEWjOIheH4Qu7PHFqMSSGmqLn2ahHMx8T7FyaknlJe3U0X/4CPqbYCvUp0/DfXD9iKHiPAzZYLYZoK1EaEvltziABI/XotBxxmPUjwwdiYPrpQ6taa8v9tnpffxgYIzZHrJp0q4cP3H/Ur4bPd5oL0HR4Rfe9agS/lbhLL4A2Ky4x/hbjkuMXxVx4YRpCwdtwkgTQfCK/ZvDMUkaLFky62ythEOIeTvYE1KHo/Rx4e+p7xZSmJ+nSMdKxrtTQxAdrvYAvL+85RQ3LZBXULz4YtTSgFh5I86Syd0dBQweRbbwqjL/lVAb5eWM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
